### ISSUE TITLE
Request to Contribute New Code and Add Hacktoberfest2023 Tag

### ISSUE THREAD

**Issue by ShaswatShrivas** [typhonshambo/coding-problem-database#1]
Hello @typhonshambo,
I'm interested in contributing to this repository by adding new code that is not currently present. I would also like to request that you add the "hacktoberfest2023" tag.

Contributing to open source projects is an excellent way to upgrade my skills and collaborate with the community. I believe this will be a valuable addition to the project and would love the opportunity to work on it.

Could you please consider assigning this issue to me? I'm excited to get started.

Thank you!

**Comment by typhonshambo** [comment]
Currently this repo. has no issue but you can contribute by posting a new coding problem (it can be from leetcode or gfg). and your answer to that problem. 
procedure is given in the Readme.md

**Comment by ShaswatShrivas** [comment]
Thank you very much.
