### ISSUE TITLE
Please add these tags in my pull request.

### ISSUE THREAD

**Issue by ShaswatShrivas** [typhonshambo/coding-problem-database#3]
Hey @typhonshambo ,
In order to get validated in Hacktoberfest-23 my pr should have labels
Hacktoberfest23 and Hacktoberfest accepted 
So can you please add those labels.
It will be very much appreciated.

**Comment by typhonshambo** [comment]
kindly check your hacktoberfest profile if the PR shows or not. I think the label i added is fine and it should work. Check once and ping me back

**Comment by ShaswatShrivas** [comment]
it is still showing non - partcipating.
img1
![Screenshot 2023-10-22 203632](https://github.com/typhonshambo/coding-problem-database/assets/103164388/cdb4683d-ad5b-4686-b084-3be1f4e872ee)


img2
![Screenshot 2023-10-22 203650](https://github.com/typhonshambo/coding-problem-database/assets/103164388/7c383b70-ffdf-4e15-9f69-58084dbf6aac)

**Comment by typhonshambo** [comment]
can you PR again, just making a small changes in the code.. like adding any semicolon or wide-space in ur readme. I would again add the proper labels before merging

**Comment by ShaswatShrivas** [comment]
done

**Comment by typhonshambo** [comment]
Well i have merged it! update me if it works fine!

**Comment by ShaswatShrivas** [comment]
yes Thanks a lot. I will try to upload new code.
